/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "fragment ControlListFields on Control {\n  id\n  title\n  description\n  category\n  status\n}\n\nfragment ControlEditFields on Control {\n  id\n  title\n  description\n  category\n  status\n}\n\nquery GetControls {\n  controls {\n    ...ControlListFields\n    ...ControlEditFields\n  }\n}\n\nmutation CreateControl($input: CreateControlInput!) {\n  createControl(input: $input) {\n    id\n    title\n    description\n    category\n    status\n  }\n}\n\nmutation UpdateControl($input: UpdateControlInput!) {\n  updateControl(input: $input) {\n    id\n    title\n    description\n    category\n    status\n  }\n}\n\nmutation UpdateControlStatus($input: UpdateControlStatusInput!) {\n  updateControlStatus(input: $input) {\n    id\n    status\n  }\n}\n\nmutation DeleteControl($id: ID!) {\n  deleteControl(id: $id)\n}": typeof types.ControlListFieldsFragmentDoc,
    "fragment OwnerListFields on Owner {\n  id\n  name\n  email\n}\n\nfragment OwnerEditFields on Owner {\n  id\n  name\n  email\n}\n\nquery GetOwners {\n  owners {\n    ...OwnerListFields\n    ...OwnerEditFields\n  }\n}\n\nmutation CreateOwner($input: CreateOwnerInput!) {\n  createOwner(input: $input) {\n    id\n    name\n    email\n  }\n}\n\nmutation UpdateOwner($input: UpdateOwnerInput!) {\n  updateOwner(input: $input) {\n    id\n    name\n    email\n  }\n}\n\nmutation DeleteOwner($id: ID!) {\n  deleteOwner(id: $id)\n}": typeof types.OwnerListFieldsFragmentDoc,
    "fragment TaskListFields on Task {\n  id\n  description\n  dueDate\n  completed\n  control {\n    title\n  }\n  owner {\n    name\n  }\n}\n\nfragment TaskEditFields on Task {\n  id\n  description\n  notes\n  dueDate\n  control {\n    id\n    title\n  }\n  owner {\n    id\n    name\n  }\n}\n\nquery GetTasks {\n  tasks {\n    ...TaskListFields\n    ...TaskEditFields\n  }\n}\n\nquery GetTasksByControl($controlId: ID!) {\n  tasksByControl(controlId: $controlId) {\n    id\n    description\n    notes\n    completed\n    dueDate\n    owner {\n      id\n      name\n      email\n    }\n  }\n}\n\nmutation CreateTask($input: CreateTaskInput!) {\n  createTask(input: $input) {\n    id\n    description\n    notes\n    completed\n    dueDate\n    control {\n      id\n      title\n    }\n    owner {\n      id\n      name\n    }\n  }\n}\n\nmutation CompleteTask($id: ID!) {\n  completeTask(id: $id) {\n    id\n    completed\n  }\n}\n\nmutation UpdateTask($input: UpdateTaskInput!) {\n  updateTask(input: $input) {\n    id\n    description\n    notes\n    dueDate\n    control {\n      id\n      title\n    }\n    owner {\n      id\n      name\n    }\n  }\n}\n\nmutation DeleteTask($id: ID!) {\n  deleteTask(id: $id)\n}": typeof types.TaskListFieldsFragmentDoc,
};
const documents: Documents = {
    "fragment ControlListFields on Control {\n  id\n  title\n  description\n  category\n  status\n}\n\nfragment ControlEditFields on Control {\n  id\n  title\n  description\n  category\n  status\n}\n\nquery GetControls {\n  controls {\n    ...ControlListFields\n    ...ControlEditFields\n  }\n}\n\nmutation CreateControl($input: CreateControlInput!) {\n  createControl(input: $input) {\n    id\n    title\n    description\n    category\n    status\n  }\n}\n\nmutation UpdateControl($input: UpdateControlInput!) {\n  updateControl(input: $input) {\n    id\n    title\n    description\n    category\n    status\n  }\n}\n\nmutation UpdateControlStatus($input: UpdateControlStatusInput!) {\n  updateControlStatus(input: $input) {\n    id\n    status\n  }\n}\n\nmutation DeleteControl($id: ID!) {\n  deleteControl(id: $id)\n}": types.ControlListFieldsFragmentDoc,
    "fragment OwnerListFields on Owner {\n  id\n  name\n  email\n}\n\nfragment OwnerEditFields on Owner {\n  id\n  name\n  email\n}\n\nquery GetOwners {\n  owners {\n    ...OwnerListFields\n    ...OwnerEditFields\n  }\n}\n\nmutation CreateOwner($input: CreateOwnerInput!) {\n  createOwner(input: $input) {\n    id\n    name\n    email\n  }\n}\n\nmutation UpdateOwner($input: UpdateOwnerInput!) {\n  updateOwner(input: $input) {\n    id\n    name\n    email\n  }\n}\n\nmutation DeleteOwner($id: ID!) {\n  deleteOwner(id: $id)\n}": types.OwnerListFieldsFragmentDoc,
    "fragment TaskListFields on Task {\n  id\n  description\n  dueDate\n  completed\n  control {\n    title\n  }\n  owner {\n    name\n  }\n}\n\nfragment TaskEditFields on Task {\n  id\n  description\n  notes\n  dueDate\n  control {\n    id\n    title\n  }\n  owner {\n    id\n    name\n  }\n}\n\nquery GetTasks {\n  tasks {\n    ...TaskListFields\n    ...TaskEditFields\n  }\n}\n\nquery GetTasksByControl($controlId: ID!) {\n  tasksByControl(controlId: $controlId) {\n    id\n    description\n    notes\n    completed\n    dueDate\n    owner {\n      id\n      name\n      email\n    }\n  }\n}\n\nmutation CreateTask($input: CreateTaskInput!) {\n  createTask(input: $input) {\n    id\n    description\n    notes\n    completed\n    dueDate\n    control {\n      id\n      title\n    }\n    owner {\n      id\n      name\n    }\n  }\n}\n\nmutation CompleteTask($id: ID!) {\n  completeTask(id: $id) {\n    id\n    completed\n  }\n}\n\nmutation UpdateTask($input: UpdateTaskInput!) {\n  updateTask(input: $input) {\n    id\n    description\n    notes\n    dueDate\n    control {\n      id\n      title\n    }\n    owner {\n      id\n      name\n    }\n  }\n}\n\nmutation DeleteTask($id: ID!) {\n  deleteTask(id: $id)\n}": types.TaskListFieldsFragmentDoc,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment ControlListFields on Control {\n  id\n  title\n  description\n  category\n  status\n}\n\nfragment ControlEditFields on Control {\n  id\n  title\n  description\n  category\n  status\n}\n\nquery GetControls {\n  controls {\n    ...ControlListFields\n    ...ControlEditFields\n  }\n}\n\nmutation CreateControl($input: CreateControlInput!) {\n  createControl(input: $input) {\n    id\n    title\n    description\n    category\n    status\n  }\n}\n\nmutation UpdateControl($input: UpdateControlInput!) {\n  updateControl(input: $input) {\n    id\n    title\n    description\n    category\n    status\n  }\n}\n\nmutation UpdateControlStatus($input: UpdateControlStatusInput!) {\n  updateControlStatus(input: $input) {\n    id\n    status\n  }\n}\n\nmutation DeleteControl($id: ID!) {\n  deleteControl(id: $id)\n}"): (typeof documents)["fragment ControlListFields on Control {\n  id\n  title\n  description\n  category\n  status\n}\n\nfragment ControlEditFields on Control {\n  id\n  title\n  description\n  category\n  status\n}\n\nquery GetControls {\n  controls {\n    ...ControlListFields\n    ...ControlEditFields\n  }\n}\n\nmutation CreateControl($input: CreateControlInput!) {\n  createControl(input: $input) {\n    id\n    title\n    description\n    category\n    status\n  }\n}\n\nmutation UpdateControl($input: UpdateControlInput!) {\n  updateControl(input: $input) {\n    id\n    title\n    description\n    category\n    status\n  }\n}\n\nmutation UpdateControlStatus($input: UpdateControlStatusInput!) {\n  updateControlStatus(input: $input) {\n    id\n    status\n  }\n}\n\nmutation DeleteControl($id: ID!) {\n  deleteControl(id: $id)\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment OwnerListFields on Owner {\n  id\n  name\n  email\n}\n\nfragment OwnerEditFields on Owner {\n  id\n  name\n  email\n}\n\nquery GetOwners {\n  owners {\n    ...OwnerListFields\n    ...OwnerEditFields\n  }\n}\n\nmutation CreateOwner($input: CreateOwnerInput!) {\n  createOwner(input: $input) {\n    id\n    name\n    email\n  }\n}\n\nmutation UpdateOwner($input: UpdateOwnerInput!) {\n  updateOwner(input: $input) {\n    id\n    name\n    email\n  }\n}\n\nmutation DeleteOwner($id: ID!) {\n  deleteOwner(id: $id)\n}"): (typeof documents)["fragment OwnerListFields on Owner {\n  id\n  name\n  email\n}\n\nfragment OwnerEditFields on Owner {\n  id\n  name\n  email\n}\n\nquery GetOwners {\n  owners {\n    ...OwnerListFields\n    ...OwnerEditFields\n  }\n}\n\nmutation CreateOwner($input: CreateOwnerInput!) {\n  createOwner(input: $input) {\n    id\n    name\n    email\n  }\n}\n\nmutation UpdateOwner($input: UpdateOwnerInput!) {\n  updateOwner(input: $input) {\n    id\n    name\n    email\n  }\n}\n\nmutation DeleteOwner($id: ID!) {\n  deleteOwner(id: $id)\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "fragment TaskListFields on Task {\n  id\n  description\n  dueDate\n  completed\n  control {\n    title\n  }\n  owner {\n    name\n  }\n}\n\nfragment TaskEditFields on Task {\n  id\n  description\n  notes\n  dueDate\n  control {\n    id\n    title\n  }\n  owner {\n    id\n    name\n  }\n}\n\nquery GetTasks {\n  tasks {\n    ...TaskListFields\n    ...TaskEditFields\n  }\n}\n\nquery GetTasksByControl($controlId: ID!) {\n  tasksByControl(controlId: $controlId) {\n    id\n    description\n    notes\n    completed\n    dueDate\n    owner {\n      id\n      name\n      email\n    }\n  }\n}\n\nmutation CreateTask($input: CreateTaskInput!) {\n  createTask(input: $input) {\n    id\n    description\n    notes\n    completed\n    dueDate\n    control {\n      id\n      title\n    }\n    owner {\n      id\n      name\n    }\n  }\n}\n\nmutation CompleteTask($id: ID!) {\n  completeTask(id: $id) {\n    id\n    completed\n  }\n}\n\nmutation UpdateTask($input: UpdateTaskInput!) {\n  updateTask(input: $input) {\n    id\n    description\n    notes\n    dueDate\n    control {\n      id\n      title\n    }\n    owner {\n      id\n      name\n    }\n  }\n}\n\nmutation DeleteTask($id: ID!) {\n  deleteTask(id: $id)\n}"): (typeof documents)["fragment TaskListFields on Task {\n  id\n  description\n  dueDate\n  completed\n  control {\n    title\n  }\n  owner {\n    name\n  }\n}\n\nfragment TaskEditFields on Task {\n  id\n  description\n  notes\n  dueDate\n  control {\n    id\n    title\n  }\n  owner {\n    id\n    name\n  }\n}\n\nquery GetTasks {\n  tasks {\n    ...TaskListFields\n    ...TaskEditFields\n  }\n}\n\nquery GetTasksByControl($controlId: ID!) {\n  tasksByControl(controlId: $controlId) {\n    id\n    description\n    notes\n    completed\n    dueDate\n    owner {\n      id\n      name\n      email\n    }\n  }\n}\n\nmutation CreateTask($input: CreateTaskInput!) {\n  createTask(input: $input) {\n    id\n    description\n    notes\n    completed\n    dueDate\n    control {\n      id\n      title\n    }\n    owner {\n      id\n      name\n    }\n  }\n}\n\nmutation CompleteTask($id: ID!) {\n  completeTask(id: $id) {\n    id\n    completed\n  }\n}\n\nmutation UpdateTask($input: UpdateTaskInput!) {\n  updateTask(input: $input) {\n    id\n    description\n    notes\n    dueDate\n    control {\n      id\n      title\n    }\n    owner {\n      id\n      name\n    }\n  }\n}\n\nmutation DeleteTask($id: ID!) {\n  deleteTask(id: $id)\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;